version: '3'
services:
    db:
        image: postgres:15
        restart: always
        env_file:
          - .env
        environment:
          POSTGRES_PASSWORD: 123
        ports:
          - "5433"
        volumes:
            - pgdata:/var/lib/postgresql/data

    web:
        build: .
        command: >
          bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
        ports:
          - "8001:8001"
        restart: always

    bot:
        build: .
        command: >
          bash -c "cd bot && python3 bot.py"
        restart: always

    redis:
        image: redis:6.2.5-alpine
        restart: always

    celery:
        build: .
        command: >
          sh -c "celery -A cars worker -l info"
        volumes:
          - project:/usr/src/app/
        depends_on:
          - redis
          - db
          - web
        restart: always

    celery-beat:
        build: .
        command: >
          sh -c "celery -A cars beat -l info"
        volumes:
          - project:/usr/src/app/
        depends_on:
          - db
          - redis
          - web
        restart: always

    

volumes:
  db_data:
  pgdata:
  project:


