# Generated by Django 3.2 on 2023-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_subscriptions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписки'),
        ),
    ]
