# Generated by Django 3.2 on 2023-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_subscriptions_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
