# Generated by Django 3.2 on 2023-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_telegramusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
